CREATE DATABASE vticnica;
\c vticnica
CREATE TABLE stanje_vticnice(
    id_zapisa SERIAL PRIMARY KEY,
    stanje BOOLEAN NOT NULL,
    napetost NUMERIC(10,5) NOT NULL,
    frekvenca NUMERIC(10,5) NOT NULL,
    tok NUMERIC(10,5) NOT NULL,
    moc NUMERIC(10,5) NOT NULL,
    casovni_zig TIMESTAMP NOT NULL,
    tarifa NUMERIC(10,5) NOT NULL,
    valuta VARCHAR(40) NOT NULL,
    casovni_blok INT NOT NULL
);
CREATE USER vticnica_up WITH PASSWORD 'vticnica-123';
GRANT ALL PRIVILEGES ON DATABASE vticnica TO vticnica_up;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO vticnica_up;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO vticnica_up;

--ne dela
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA public TO vticnica_up; -- pa sej ni važn

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO vticnica_up;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO vticnica_up;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO vticnica_up;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO vticnica_up;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO vticnica_up;

CREATE USER vticnica_up_bralec WITH PASSWORD 'vticnica-1234';
GRANT SELECT ON ALL TABLES IN SCHEMA public TO vticnica_up_bralec;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO vticnica_up_bralec;

SELECT * FROM (
SELECT 
    DATE_TRUNC('hour', casovni_zig) AS ura,
    SUM(moc * 0.5 / 3600000) AS kwh,
    AVG(tarifa) AS tarifa
FROM stanje_vticnice
GROUP BY ura
ORDER BY ura DESC
LIMIT 24) AS zadnjih24ur ORDER  BY ura ASC;